services:
  #La web API (node)
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    labels:
      - "autoheal=true"
    develop:
      watch:
        - path: ./api/
          action: sync
          target: /usr/src/app
    container_name: ${PROJECT_NAME}-api
    ports:
      - ${HOST_PORT_API}:3000
    depends_on:
      - db  
    healthcheck:
        test: ["CMD", "mysqladmin", "-hdb", "-P3306", "ping", "--silent"]
        timeout: 3s
        interval: 4s
        retries: 10
    command: ["./node_modules/nodemon/bin/nodemon.js", "./bin/www"]

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./dbdata:/var/lib/mysql
    ports:
      - ${HOST_PORT_DB}:3306
    container_name: ${PROJECT_NAME}-db

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    container_name: ${PROJECT_NAME}-adminer
    ports:
      - ${HOST_PORT_ADMINER}:8080
